
export const PROJECT_FORM= 'PROJECT_FORM'; 
export const GET_PROJECTS = 'GET_PROJECTS';
export const  ADD_PROJECT = 'ADD_PROJECT';
export const VALIDAR_FORMULARY = 'VALIDAR_FORMULARY';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';